// Noema Retail: Build Script
//
// PureScript のコンパイル結果を Cloudflare Workers 用にバンドルする。

import * as esbuild from 'esbuild';
import { existsSync } from 'fs';

const isProduction = process.env.NODE_ENV === 'production';

// PureScript 出力ディレクトリの確認
if (!existsSync('./output/Main/index.js')) {
  console.error('Error: PureScript output not found.');
  console.error('Run "spago build" first.');
  process.exit(1);
}

// ESBuild でバンドル
await esbuild.build({
  entryPoints: ['./packages/noema-retail/ffi/runtime.js'],
  bundle: true,
  outfile: './dist/worker.js',
  format: 'esm',
  target: 'es2022',
  platform: 'neutral',
  minify: isProduction,
  sourcemap: !isProduction,
  external: ['cloudflare:workers'],
  define: {
    'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV || 'development'),
  },
  banner: {
    js: '// Noema Retail - Generated by PureScript + ESBuild',
  },
  logLevel: 'info',
});

console.log('Bundle created: dist/worker.js');
